name: CI/CD

on: [push]

jobs:
  pylint:
    runs-on: macos-latest

    # steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out the repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out the repository code
        uses: actions/checkout@v4
      
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
          brew update
          brew install graph-tool
          brew --prefix graph-tool
          python -c "import graph_tool"

      # Add path to graph-tool to PYTHONPATH
      - name: Configure PYTHONPATH
        run: echo "PYTHONPATH=/opt/homebrew/opt/graph-tool/libexec/lib/python3.12/site-packages:\$PYTHONPATH" >> $GITHUB_ENV

      # Run pylint 
      - name: Analysing the code with pylint
        run: |
          pylint ./
